config: 
  formation_directory: "/home/patrick/uva/ros/amrl_ws/src/amrl_consensus/config/formations/"
  plan_directory: "/home/patrick/uva/ros/amrl_ws/src/amrl_consensus/config/plans/"

display:
  enabled: true

consensus:
  plan: "circle_line"
  num_robots: 4
  alpha: 1.5
  gamma: 2.0

logging:
  enabled: false
  drop_table: false
  table: "FinalResults"
  tags: "case1"
